### PR TITLE
[WFLY-12758] Add OpenTracing subsystem integration tests

### PR DESCRIPTION
**Pull request by zhantemirov**
Integration tests have been added that are verifying a new feature of configuring Jaeger tracers via WildFly SmallRye OpenTracing subsystem.

The following test cases are presented: 
1) Change the default Jaeger tracer configuration by setting the attributes in SmallRye OpenTracing subsystem and check whether these changes are propagated to a deployed application with Tracer instance.
2) Undefine default SmallRye Jaeger tracer configuration -> in that case NoopTracer should be used for deployments that are not implicitly defining desired tracer configuration. 
3) Two additional test cases with an exception thrown on a server side and service with path containing regular expressions.

Jira: https://issues.redhat.com/browse/WFLY-12758

### CODE REVIEW

**Comment by zhantemirov** [comment]
FYI @ehsavoie @rsvoboda

**Comment by rsvoboda** [comment]
There are conflicting files reported now

**Comment by ehsavoie** [comment]
@rsvoboda if you only use @zhantemirov 's commit there is no conflict.

**Comment by zhantemirov** [comment]
Tests have been combined with existing ones in https://github.com/wildfly/wildfly/pull/12836

**Pull request closed without merging**
